[project]
name = "one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ingestion-engine",
]

[tool.uv.sources]
ingestion-engine = { path = "../ingestion-engine" }
